### ISSUE TITLE
[BUG] Pairing code login mode not working anymore

### ISSUE THREAD

**Issue by alexandrereyes** [WhiskeySockets/Baileys#328]
**Describe the bug**
The auth pairing code is not working anymwore, i tried to run example.ts, the pair code shows on the console but wa doesn't notifies about it and also, the pairing code (yes, the console shows the code!) doesn't work on wa.
400 error on console:
```
{"level":10,"time":"2023-08-14T18:44:30.947Z","pid":49820,"hostname":"Desk-Ale","class":"ns","msg":"recv 63 bytes, total recv 63 bytes"}
{"level":10,"time":"2023-08-14T18:44:30.947Z","pid":49820,"hostname":"Desk-Ale","class":"ns","msg":"7679.52164-1","msg":"recv frame"}
{"level":10,"time":"2023-08-14T18:44:30.948Z","pid":49820,"hostname":"Desk-Ale","msg":"<iq from='@s.whatsapp.net' type='error' id='7679.52164-1'>\n\t\t<error code='400' text='bad-request'/>\n</iq>"}
```
I tried with 2 real numbers, no success! Anybody facing the same issue?

**To Reproduce**
Very simple: Run example.ts with --use-pairing-code and try to login

**Expected behavior**
Receive wa notification about the code and the code work on wa

**Environment (please complete the following information):**
 - Is this on a server? No
 - What do your `connectOptions` look like?  same as example.ts
 - Do you have multiple clients on the same IP? no, dev env
 - Are you using a proxy? no

**Comment by FERDIZ-afk** [comment]
I also experienced the same thing

**Comment by makanSukros** [comment]
Same here

**Comment by olalonde** [comment]
Same issue here. Getting this message right after requesting pairing code.

```ts
[15:01:52.761] DEBUG (23866): communication recv
    unhandled: true
    msgId: "31234.38503-1"
    fromMe: false
    frame: {
      "tag": "iq",
      "attrs": {
        "from": "@s.whatsapp.net",
        "type": "error",
        "id": "31234.38503-1"
      },
      "content": [
        {
          "tag": "error",
          "attrs": {
            "code": "400",
            "text": "bad-request"
          }
        }
      ]
    }
```

It was working a few days ago.

**Comment by burstfreeze** [comment]
For a test, hardcode the value in https://github.com/WhiskeySockets/Baileys/blob/49ab16f5925789b85219bec2f35686234dab08a0/src/Socket/socket.ts#L528 to `Chrome (macOS)`.

WA sends `$Browser ($OS)` and the server now seems to expect it in that very format

**Comment by Auties00** [comment]
> For a test, hardcode the value in https://github.com/WhiskeySockets/Baileys/blob/49ab16f5925789b85219bec2f35686234dab08a0/src/Socket/socket.ts#L528 to `Chrome (macOS)`.
> 
> WA sends `$Browser ($OS)` and the server now seems to expect it in that very format

Does that fix it? 
As I explained on discord it should be as easy as cloning my repo 
https://github.com/Auties00/WhatsappWebRequestAnalyzer
And seeing which nodes changed(probably something minor). 
I'd do it if I weren't on vacation

**Comment by burstfreeze** [comment]
I can't try it right now but the request payload is 14 bytes and the wa web source does what I said regarding `$Browser ($OS)`

**Comment by lyfe00011** [comment]
Chrome (Linux) - this fix it

**Comment by Salientekill** [comment]
> 

Could you tell me what I would have to change to work?

**Comment by alexandrereyes** [comment]
change yout makeWASocket method, example:

```
const sock = makeWASocket({
	browser: ['Chrome (Linux)', '', ''],
})
```

**Comment by Radit10** [comment]
It's work thank you

**Comment by A-d-i-t-h-y-a-n** [comment]
👀

**Comment by A-d-i-t-h-y-a-n** [comment]
> It's work thank you

Really 👀

**Comment by ArifzynXD** [comment]
Oke work, thks

**Comment by mkhotib20** [comment]
thanks @alexandrereyes it works

**Comment by curiousHG** [comment]
Still not working for me, I am trying using the given  Example.ts file and changing the browser to 'Chrome (Linux)' or 'Chrome (MacOS)' didn't work for me.
Every time I enter the code on my device it says incorrect code. And the logs start to give QR code for some reason after the failed attempt.

**Comment by A-d-i-t-h-y-a-n** [comment]
> Still not working for me, I am trying using the given Example.ts file and changing the browser to 'Chrome (Linux)' or 'Chrome (MacOS)' didn't work for me. Every time I enter the code on my device it says incorrect code. And the logs start to give QR code for some reason after the failed attempt.

Oh,
But in my case it's Ok
I just changed browser to Chrome (Linux)
[https://hermit.adithyan.xyz/qr](https://hermit.adithyan.xyz/qr)

**Comment by syxhri** [comment]
> Still not working for me, I am trying using the given Example.ts file and changing the browser to 'Chrome (Linux)' or 'Chrome (MacOS)' didn't work for me. Every time I enter the code on my device it says incorrect code. And the logs start to give QR code for some reason after the failed attempt.

I also experienced the same thing. But when I try to enter the phone number without the plus sign it works

**Comment by curiousHG** [comment]
> > Still not working for me, I am trying using the given Example.ts file and changing the browser to 'Chrome (Linux)' or 'Chrome (MacOS)' didn't work for me. Every time I enter the code on my device it says incorrect code. And the logs start to give QR code for some reason after the failed attempt.
> 
> I also experienced the same thing. But when I try to enter the phone number without the plus sign it works

This fixed it, Thanks!

**Comment by Arctic-beaver** [comment]
Is it still working with 'Chrome (Linux)'? 

> change yout makeWASocket method, example:
> 
> ```
> const sock = makeWASocket({
> 	browser: ['Chrome (Linux)', '', ''],
> })
> ```

**Comment by Riders004** [comment]
> It's work thank you

Can you share your code to me

**Comment by Aal-oss** [comment]
use whiskeysockets/baileys 6.4.1

**Comment by SunPandu** [comment]
Sebenarnya bisa aja program browser yah seperti ini aku pernah coba dan berhasil.

```
"use strict";
const { Boom } = require("@hapi/boom");
const NodeCache = require("node-cache");
const {
    makeWASocket,
    makeInMemoryStore,
    useMultiFileAuthState,
    fetchLatestBaileysVersion,
    makeCacheableSignalKeyStore,
    DisconnectReason,
    jidDecode,
    delay,
    proto
} = require("@whiskeysockets/baileys");
const moment = require("moment");
const fs = require("fs");

const timer = moment(new Date()).format("HH:mm:ss DD/MM/YYYY");

const logger = require("pino")({
    timestamp: function () {
        `,"time":"${new Date().toJSON()}"`;
    }
}).chlid({});
logger.level = "silent";

const useStore = !process.argv.includes("--no-store");
const usePairingCode = process.argv.includes("--use-pairing-code");

const msgRetryCounterCache = new NodeCache();

const rl = require("readline").createInterface({
    input: process.stdin,
    output: process.stdout
});

const question = text => new Promise(resolve => rl.question(text, resolve));

const store = useStore ? makeInMemoryStore({ logger }) : undefined;

store?.readFromFile("./store_multi.json");
// 10detik
setInterval(() => {
    store?.writeToFile("./store_multi.json");
}, 10000);

function uncache(module = ".") {
    return new Promise(function (resolve, reject) {
        try {
            delete require.cache[require.resolve(module)];
            resolve();
        } catch (error) {
            reject(error);
        }
    });
}

function nocache(module, cb = function () {}) {
    console.log(`module ${module} memantau perubahan data.`);
    fs.watchFile(require.resolve(module), async function () {
        await uncache(require.resolve(module));
        cb(module);
    });
}

async function connectoWhatsapps() {
    const { state, saveCreds } = await useMultiFileAuthState("@OpenWA");
    const { version, isLatest } = await fetchLatestBaileysVersion();

    const sock = makeWASocket({
        version,
        logger,
        printQRInTerminal: !usePairingCode,
        browser: ["Safari (Linux)", "browser", "1.0.0"],
        auth: {
            creds: state.creds,
            keys: makeCacheableSignalKeyStore(state.keys, logger)
        },
        msgRetryCounterCache,
        generateHighQualityLinkPreview: true,
        patchMessageBeforeSending,
        getMessage
    });

    store?.bind(sock.ev);

    require("./src/main");
    nocache("./src/main", function (module) {
        console.log(`[ WHATSAPPS BOT ] ${timer} ${module} telah di update!...`);
    });

    sock.ev.on("chats.set", function () {
        console.log("got chats", store.chats.all());
    });

    sock.ev.on("contacts.set", function () {
        console.log("got contacts", Object.values(store.contacts));
    });

    if (usePairingCode && !sock.authState.creds.registered) {
        const phoneNumber = await question(
            "Masukkan nomor telepon seluler anda: +"
        );
        if (/\d/.test(phoneNumber)) {
            const code = await sock.requestPairingCode(
                phoneNumber.replace(/[^0-9]/g, "")
            );
            console.log(
                "jika ada notif whatsapp [Memasukkan kode menautkan perangkat baru] maka sudah di pastikan berhasil!"
            );
            console.log(`pairing code: ${code.match(/.{1,4}/g).join("-")}`);
        } else {
            console.log("Nomor telepon tidak valid.");
            process.exit();
        }
    }

    const sendMessageWTyping = async (msg, jid) => {
        await sock.presenceSubscribe(jid);
        await delay(500);
        await sock.sendPresenceUpdate("composing", jid);
        await delay(2000);
        await sock.sendPresenceUpdate("paused", jid);
        await sock.sendMessage(jid, msg);
    };

    sock.ev.on("connection.update", function ({ connection, lastDisconnect }) {
        switch (connection) {
            case "close":
                switch (new Boom(lastDisconnect?.error)?.output?.statusCode) {
                    case DisconnectReason.badSession:
                        console.log(
                            `Bad Session File, hapus session dan scan scan lagi.`
                        );
                        process.exit();
                        break;
                    case DisconnectReason.connectionClosed:
                        console.log(
                            "Connection closed, menyambungkan kembali..."
                        );
                        connectoWhatsapps();
                        break;
                    case DisconnectReason.connectionLost:
                        console.log(
                            "Connection Lost from Server, menyambungkan kembali..."
                        );
                        connectoWhatsapps();
                        break;
                    case DisconnectReason.connectionReplaced:
                        console.log(
                            "Connection Replaced, sesi baru lainnya dibuka dan terhubung kembali..."
                        );
                        connectoWhatsapps();
                        break;
                    case DisconnectReason.loggedOut:
                        console.log(`Device Logged Out, scan ulang lagi.`);
                        process.exit();
                        break;
                    case DisconnectReason.restartRequired:
                        console.log("Restart Required, memulai ulang...");
                        connectoWhatsapps();
                        break;
                    case DisconnectReason.timedOut:
                        console.log(
                            "Connection TimedOut, menyambungkan kembali..."
                        );
                        connectoWhatsapps();
                        break;
                    case DisconnectReason.Multidevicemismatch:
                        console.log("Multi device mismatch, scan ulang lagi.");
                        process.exit();
                        break;
                    default:
                        console.log(``);
                }
                break;
            case "connecting":
                console.log(
                    `using WA v${version.join(".")}, isLatest ${isLatest}`
                );
                break;
            case "open":
                console.log(" nama :", sock.user.name);
                console.log(" nomor:", sock.user.id.split(":")[0]);
                rl.close();
                break;
            default:
        }
    });

    sock.ev.on("creds.update", function () {
        saveCreds();
    });

    sock.ev.on("messages.upsert", function ({ messages, type }) {
        console.log("recv messages ", JSON.stringify(messages, undefined, 2));
    });

    sock.decodeJid = function (jid) {
        if (!jid) return jid;
        if (/:\d+@/gi.test(jid)) {
            const decode = jidDecode(jid) || {};
            return (
                (decode.user &&
                    decode.server &&
                    decode.user + "@" + decode.server) ||
                jid
            );
        }
    };

    sock.ev.on("contacts.update", function (update) {
        for (const contact of update) {
            const id = sock.decodeJid(contact.id);
            if (store && store.contacts)
                store.contacts[id] = {
                    id,
                    name: contact.notify
                };
        }
    });

    sock.ev.on(
        "group-participants.update",
        function ({ id, participants, action }) {}
    );

    sock.reply = async function (from, content, message) {
        await sock.sendMessage(from, { text: content }, { quoted: message });
    };

    return sock;

    function patchMessageBeforeSending(message) {
        const requiresPatch = !!(
            message.buttonsMessage ||
            message.templateMessage ||
            message.listMessage
        );
        if (requiresPatch) {
            message = {
                viewOnceMessage: {
                    message: {
                        messageContextInfo: {
                            deviceListMetadataVersion: 2,
                            deviceListMetadata: {}
                        },
                        ...message
                    }
                }
            };
        }
        return message;
    }

    async function getMessage(key) {
        if (store) {
            const msg = await store.loadMessage(key.remoteJid, key.id);
            return msg?.message || undefined;
        }
        // only if store is present
        return proto.Message.fromObject({});
    }
}

/*
const currentModulePath = __filename;

fs.witchFile(currentModulePath, function () {
    fs.unwatchFile(currentModulePath);
    console.log(
        `Module ${require("path").basename(
            currentModulePath
        )} has been updated.`
    );
    delete require.cache[currentModulePath];
    require(currentModulePath);
});
*/

```

**Comment by SunPandu** [comment]
Ini cara yang paling sempurna dan aman untuk pairing code dan saya pernah coba dan berhasil, menggunakan browser Safari (Linux) browser 1.0.0


```
"use strict";
const { Boom } = require("@hapi/boom");
const NodeCache = require("node-cache");
const {
    makeWASocket,
    makeInMemoryStore,
    useMultiFileAuthState,
    fetchLatestBaileysVersion,
    makeCacheableSignalKeyStore,
    DisconnectReason,
    jidDecode,
    delay,
    proto
} = require("@whiskeysockets/baileys");
const moment = require("moment");
const fs = require("fs");

const timer = moment(new Date()).format("HH:mm:ss DD/MM/YYYY");

const logger = require("pino")({
    timestamp: () => `,"time":"${new Date().toJSON()}"`
}).child({});
logger.level = "silent";

const useStore = !process.argv.includes("--no-store");
const usePairingCode = process.argv.includes("--use-pairing-code");

const msgRetryCounterCache = new NodeCache();

const rl = require("readline").createInterface({
    input: process.stdin,
    output: process.stdout
});

const question = text => new Promise(resolve => rl.question(text, resolve));

const store = useStore ? makeInMemoryStore({ logger }) : undefined;

store?.readFromFile("./store_multi.json");
// 10detik
setInterval(() => {
    store?.writeToFile("./store_multi.json");
}, 10000);

function uncache(module = ".") {
    return new Promise(function (resolve, reject) {
        try {
            delete require.cache[require.resolve(module)];
            resolve();
        } catch (error) {
            reject(error);
        }
    });
}

function nocache(module, cb = function () {}) {
    console.log(`module ${module} memantau perubahan data.\n`);
    fs.watchFile(require.resolve(module), async function () {
        await uncache(require.resolve(module));
        cb(module);
    });
}

async function connectoWhatsapps() {
    const { state, saveCreds } = await useMultiFileAuthState("@OpenWA");
    const { version, isLatest } = await fetchLatestBaileysVersion();

    const sock = makeWASocket({
        version,
        logger,
        printQRInTerminal: !usePairingCode,
        browser: ["Safari (Linux)", "browser", "1.0.0"],
        auth: {
            creds: state.creds,
            keys: makeCacheableSignalKeyStore(state.keys, logger)
        },
        msgRetryCounterCache,
        generateHighQualityLinkPreview: true,
        patchMessageBeforeSending,
        getMessage
    });

    store?.bind(sock.ev);

    require("./index");
    nocache("./index", function (module) {
        console.log(
            `\n[ WHATSAPPS BOT ] ${timer} ${module} telah di update!...`
        );
    });

    sock.ev.on("chats.set", function () {
        console.log("got chats", store.chats.all());
    });

    sock.ev.on("contacts.set", function () {
        console.log("got contacts", Object.values(store.contacts));
    });

    if (usePairingCode && !sock.authState.creds.registered) {
        const phoneNumber = await question(
            "Masukkan nomor telepon seluler anda: +"
        );
        if (/\d/.test(phoneNumber)) {
            const code = await sock.requestPairingCode(
                phoneNumber.replace(/[^0-9]/g, "")
            );
            console.log(
                "jika ada notif whatsapp [Memasukkan kode menautkan perangkat baru] maka sudah di pastikan berhasil!"
            );
            console.log(`pairing code: ${code.match(/.{1,4}/g).join("-")}`);
        } else {
            console.log("Nomor telepon tidak valid.");
            process.exit();
        }
    }

    const sendMessageWTyping = async (msg, jid) => {
        await sock.presenceSubscribe(jid);
        await delay(500);
        await sock.sendPresenceUpdate("composing", jid);
        await delay(2000);
        await sock.sendPresenceUpdate("paused", jid);
        await sock.sendMessage(jid, msg);
    };

    sock.ev.on("connection.update", function ({ connection, lastDisconnect }) {
        switch (connection) {
            case "close":
                switch (new Boom(lastDisconnect?.error)?.output?.statusCode) {
                    case DisconnectReason.badSession:
                        console.log(
                            `Bad Session File, hapus session dan scan scan lagi.`
                        );
                        process.exit();
                        break;
                    case DisconnectReason.connectionClosed:
                        console.log(
                            "Connection closed, menyambungkan kembali..."
                        );
                        connectoWhatsapps();
                        break;
                    case DisconnectReason.connectionLost:
                        console.log(
                            "Connection Lost from Server, menyambungkan kembali..."
                        );
                        connectoWhatsapps();
                        break;
                    case DisconnectReason.connectionReplaced:
                        console.log(
                            "Connection Replaced, sesi baru lainnya dibuka dan terhubung kembali..."
                        );
                        connectoWhatsapps();
                        break;
                    case DisconnectReason.loggedOut:
                        console.log(`Device Logged Out, scan ulang lagi.`);
                        process.exit();
                        break;
                    case DisconnectReason.restartRequired:
                        console.log("Restart Required, memulai ulang...");
                        connectoWhatsapps();
                        break;
                    case DisconnectReason.timedOut:
                        console.log(
                            "Connection TimedOut, menyambungkan kembali..."
                        );
                        connectoWhatsapps();
                        break;
                    case DisconnectReason.Multidevicemismatch:
                        console.log("Multi device mismatch, scan ulang lagi.");
                        process.exit();
                        break;
                    default:
                        console.log(``);
                }
                break;
            case "connecting":
                console.log(
                    `using WA v${version.join(".")}, isLatest ${isLatest}`
                );
                break;
            case "open":
                console.log(" nama :", sock.user.name);
                console.log(" nomor:", sock.user.id.split(":")[0]);
                rl.close();
                break;
            default:
        }
    });

    sock.ev.on("creds.update", function () {
        saveCreds();
    });

    sock.ev.on("messages.upsert", function ({ messages, type }) {
        console.log("recv messages ", JSON.stringify(messages, undefined, 2));
    });

    sock.decodeJid = function (jid) {
        if (!jid) return jid;
        if (/:\d+@/gi.test(jid)) {
            const decode = jidDecode(jid) || {};
            return (
                (decode.user &&
                    decode.server &&
                    decode.user + "@" + decode.server) ||
                jid
            );
        }
    };

    sock.ev.on("contacts.update", function (update) {
        for (const contact of update) {
            const id = sock.decodeJid(contact.id);
            if (store && store.contacts)
                store.contacts[id] = {
                    id,
                    name: contact.notify
                };
        }
    });

    sock.ev.on(
        "group-participants.update",
        function ({ id, participants, action }) {}
    );

    sock.reply = async function (from, content, message) {
        await sock.sendMessage(from, { text: content }, { quoted: message });
    };

    return sock;

    function patchMessageBeforeSending(message) {
        const requiresPatch = !!(
            message.buttonsMessage ||
            message.templateMessage ||
            message.listMessage
        );
        if (requiresPatch) {
            message = {
                viewOnceMessage: {
                    message: {
                        messageContextInfo: {
                            deviceListMetadataVersion: 2,
                            deviceListMetadata: {}
                        },
                        ...message
                    }
                }
            };
        }
        return message;
    }

    async function getMessage(key) {
        if (store) {
            const msg = await store.loadMessage(key.remoteJid, key.id);
            return msg?.message || undefined;
        }
        // only if store is present
        return proto.Message.fromObject({});
    }
}

connectoWhatsapps();

```

**Comment by Riders004** [comment]
> Ini cara yang paling sempurna dan aman untuk pairing code dan saya pernah coba dan berhasil, menggunakan browser Safari (Linux) browser 1.0.0
> 
> ```
> "use strict";
> const { Boom } = require("@hapi/boom");
> const NodeCache = require("node-cache");
> const {
>     makeWASocket,
>     makeInMemoryStore,
>     useMultiFileAuthState,
>     fetchLatestBaileysVersion,
>     makeCacheableSignalKeyStore,
>     DisconnectReason,
>     jidDecode,
>     delay,
>     proto
> } = require("@whiskeysockets/baileys");
> const moment = require("moment");
> const fs = require("fs");
> 
> const timer = moment(new Date()).format("HH:mm:ss DD/MM/YYYY");
> 
> const logger = require("pino")({
>     timestamp: () => `,"time":"${new Date().toJSON()}"`
> }).child({});
> logger.level = "silent";
> 
> const useStore = !process.argv.includes("--no-store");
> const usePairingCode = process.argv.includes("--use-pairing-code");
> 
> const msgRetryCounterCache = new NodeCache();
> 
> const rl = require("readline").createInterface({
>     input: process.stdin,
>     output: process.stdout
> });
> 
> const question = text => new Promise(resolve => rl.question(text, resolve));
> 
> const store = useStore ? makeInMemoryStore({ logger }) : undefined;
> 
> store?.readFromFile("./store_multi.json");
> // 10detik
> setInterval(() => {
>     store?.writeToFile("./store_multi.json");
> }, 10000);
> 
> function uncache(module = ".") {
>     return new Promise(function (resolve, reject) {
>         try {
>             delete require.cache[require.resolve(module)];
>             resolve();
>         } catch (error) {
>             reject(error);
>         }
>     });
> }
> 
> function nocache(module, cb = function () {}) {
>     console.log(`module ${module} memantau perubahan data.\n`);
>     fs.watchFile(require.resolve(module), async function () {
>         await uncache(require.resolve(module));
>         cb(module);
>     });
> }
> 
> async function connectoWhatsapps() {
>     const { state, saveCreds } = await useMultiFileAuthState("@OpenWA");
>     const { version, isLatest } = await fetchLatestBaileysVersion();
> 
>     const sock = makeWASocket({
>         version,
>         logger,
>         printQRInTerminal: !usePairingCode,
>         browser: ["Safari (Linux)", "browser", "1.0.0"],
>         auth: {
>             creds: state.creds,
>             keys: makeCacheableSignalKeyStore(state.keys, logger)
>         },
>         msgRetryCounterCache,
>         generateHighQualityLinkPreview: true,
>         patchMessageBeforeSending,
>         getMessage
>     });
> 
>     store?.bind(sock.ev);
> 
>     require("./index");
>     nocache("./index", function (module) {
>         console.log(
>             `\n[ WHATSAPPS BOT ] ${timer} ${module} telah di update!...`
>         );
>     });
> 
>     sock.ev.on("chats.set", function () {
>         console.log("got chats", store.chats.all());
>     });
> 
>     sock.ev.on("contacts.set", function () {
>         console.log("got contacts", Object.values(store.contacts));
>     });
> 
>     if (usePairingCode && !sock.authState.creds.registered) {
>         const phoneNumber = await question(
>             "Masukkan nomor telepon seluler anda: +"
>         );
>         if (/\d/.test(phoneNumber)) {
>             const code = await sock.requestPairingCode(
>                 phoneNumber.replace(/[^0-9]/g, "")
>             );
>             console.log(
>                 "jika ada notif whatsapp [Memasukkan kode menautkan perangkat baru] maka sudah di pastikan berhasil!"
>             );
>             console.log(`pairing code: ${code.match(/.{1,4}/g).join("-")}`);
>         } else {
>             console.log("Nomor telepon tidak valid.");
>             process.exit();
>         }
>     }
> 
>     const sendMessageWTyping = async (msg, jid) => {
>         await sock.presenceSubscribe(jid);
>         await delay(500);
>         await sock.sendPresenceUpdate("composing", jid);
>         await delay(2000);
>         await sock.sendPresenceUpdate("paused", jid);
>         await sock.sendMessage(jid, msg);
>     };
> 
>     sock.ev.on("connection.update", function ({ connection, lastDisconnect }) {
>         switch (connection) {
>             case "close":
>                 switch (new Boom(lastDisconnect?.error)?.output?.statusCode) {
>                     case DisconnectReason.badSession:
>                         console.log(
>                             `Bad Session File, hapus session dan scan scan lagi.`
>                         );
>                         process.exit();
>                         break;
>                     case DisconnectReason.connectionClosed:
>                         console.log(
>                             "Connection closed, menyambungkan kembali..."
>                         );
>                         connectoWhatsapps();
>                         break;
>                     case DisconnectReason.connectionLost:
>                         console.log(
>                             "Connection Lost from Server, menyambungkan kembali..."
>                         );
>                         connectoWhatsapps();
>                         break;
>                     case DisconnectReason.connectionReplaced:
>                         console.log(
>                             "Connection Replaced, sesi baru lainnya dibuka dan terhubung kembali..."
>                         );
>                         connectoWhatsapps();
>                         break;
>                     case DisconnectReason.loggedOut:
>                         console.log(`Device Logged Out, scan ulang lagi.`);
>                         process.exit();
>                         break;
>                     case DisconnectReason.restartRequired:
>                         console.log("Restart Required, memulai ulang...");
>                         connectoWhatsapps();
>                         break;
>                     case DisconnectReason.timedOut:
>                         console.log(
>                             "Connection TimedOut, menyambungkan kembali..."
>                         );
>                         connectoWhatsapps();
>                         break;
>                     case DisconnectReason.Multidevicemismatch:
>                         console.log("Multi device mismatch, scan ulang lagi.");
>                         process.exit();
>                         break;
>                     default:
>                         console.log(``);
>                 }
>                 break;
>             case "connecting":
>                 console.log(
>                     `using WA v${version.join(".")}, isLatest ${isLatest}`
>                 );
>                 break;
>             case "open":
>                 console.log(" nama :", sock.user.name);
>                 console.log(" nomor:", sock.user.id.split(":")[0]);
>                 rl.close();
>                 break;
>             default:
>         }
>     });
> 
>     sock.ev.on("creds.update", function () {
>         saveCreds();
>     });
> 
>     sock.ev.on("messages.upsert", function ({ messages, type }) {
>         console.log("recv messages ", JSON.stringify(messages, undefined, 2));
>     });
> 
>     sock.decodeJid = function (jid) {
>         if (!jid) return jid;
>         if (/:\d+@/gi.test(jid)) {
>             const decode = jidDecode(jid) || {};
>             return (
>                 (decode.user &&
>                     decode.server &&
>                     decode.user + "@" + decode.server) ||
>                 jid
>             );
>         }
>     };
> 
>     sock.ev.on("contacts.update", function (update) {
>         for (const contact of update) {
>             const id = sock.decodeJid(contact.id);
>             if (store && store.contacts)
>                 store.contacts[id] = {
>                     id,
>                     name: contact.notify
>                 };
>         }
>     });
> 
>     sock.ev.on(
>         "group-participants.update",
>         function ({ id, participants, action }) {}
>     );
> 
>     sock.reply = async function (from, content, message) {
>         await sock.sendMessage(from, { text: content }, { quoted: message });
>     };
> 
>     return sock;
> 
>     function patchMessageBeforeSending(message) {
>         const requiresPatch = !!(
>             message.buttonsMessage ||
>             message.templateMessage ||
>             message.listMessage
>         );
>         if (requiresPatch) {
>             message = {
>                 viewOnceMessage: {
>                     message: {
>                         messageContextInfo: {
>                             deviceListMetadataVersion: 2,
>                             deviceListMetadata: {}
>                         },
>                         ...message
>                     }
>                 }
>             };
>         }
>         return message;
>     }
> 
>     async function getMessage(key) {
>         if (store) {
>             const msg = await store.loadMessage(key.remoteJid, key.id);
>             return msg?.message || undefined;
>         }
>         // only if store is present
>         return proto.Message.fromObject({});
>     }
> }
> 
> connectoWhatsapps();
> ```

U can use chrome for faster

**Comment by PurpShell** [comment]
This issue is fixed from my analysis.

**Comment by ibnusurkati** [comment]
use this, it's works for me
```
...
browser: Browsers.ubuntu('CHROME'),
...
```

because if we look at the original source, array browser[1] refers to an enum that uses uppercase letters.

<img width="322" alt="Screenshot 2024-01-21 at 22 44 57" src="https://github.com/WhiskeySockets/Baileys/assets/43799707/4babf2e7-21dc-4602-b467-a90fe735b153">

<img width="419" alt="Screenshot 2024-01-21 at 22 45 33" src="https://github.com/WhiskeySockets/Baileys/assets/43799707/ee68e1af-5509-4a63-a8c4-d9e1dc944bfd">

![image](https://github.com/WhiskeySockets/Baileys/assets/43799707/73bfee22-87d8-4758-8882-a3a1688e10c9)

**Comment by Riders004** [comment]
> use this, it's works for me
> 
> ```
> ...
> browser: Browsers.ubuntu('CHROME'),
> ...
> ```
> 
> because if we look at the original source, array browser[1] refers to an enum that uses uppercase letters.
> 
> <img alt="Screenshot 2024-01-21 at 22 44 57" width="322" src="https://private-user-images.githubusercontent.com/43799707/298394254-4babf2e7-21dc-4602-b467-a90fe735b153.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NTQ1MDcsIm5iZiI6MTcwNTg1NDIwNywicGF0aCI6Ii80Mzc5OTcwNy8yOTgzOTQyNTQtNGJhYmYyZTctMjFkYy00NjAyLWI0NjctYTkwZmU3MzViMTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDE2MjMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5MzVjY2Q0ZmMzZDQ3N2FjYWY5ZDcyMzc1OTc2N2JlNjk2NWYzYjVhODdkMjYxMjJmZjg4YzNiYTM5Y2JhMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TcG9geKYWtAq7usCmfnp8j5ilsljE2a-sOmiWw-bSok"> <img alt="Screenshot 2024-01-21 at 22 45 33" width="419" src="https://private-user-images.githubusercontent.com/43799707/298394291-ee68e1af-5509-4a63-a8c4-d9e1dc944bfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NTQ1MDcsIm5iZiI6MTcwNTg1NDIwNywicGF0aCI6Ii80Mzc5OTcwNy8yOTgzOTQyOTEtZWU2OGUxYWYtNTUwOS00YTYzLWE4YzQtZDllMWRjOTQ0YmZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDE2MjMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiZmU2NmZkN2YxMGFhOGMwMzZhYzc4OTgyYTM4ZmMxNDY0ODI4OTE5ZjkyNmEwOGFkMGY5ZmIwYjI4M2QyMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P3I5JFru2kfrvQCkR-NbgD7qEs2oWx6a-hCWc_oXpNo">

Well it's got fixed

**Comment by Jann-X** [comment]
I've used it before. but still not working. what should I replace?

> change yout makeWASocket method, example:
> 
> ```
> const sock = makeWASocket({
> 	browser: ['Chrome (Linux)', '', ''],
> })
> ```

**Comment by Riders004** [comment]
> I've used it before. but still not working. what should I replace?
> 
> > change yout makeWASocket method, example:
> > ```
> > const sock = makeWASocket({
> > 	browser: ['Chrome (Linux)', '', ''],
> > })
> > ```

const sock = makeWASocket({
	browser: ['ubuntu', 'chrome', ''],
})

**Comment by Ytsixx** [comment]
![IMG_20240424_063707](https://github.com/WhiskeySockets/Baileys/assets/138830763/d02bcdb2-bb2e-47c5-a3d6-a85ef3fb6031)
Hello 👋 I hope everyone is well I would like to know how I can add a button to my project I have had more than 3 weeks without success

**Comment by Riders004** [comment]
> ![IMG_20240424_063707](https://private-user-images.githubusercontent.com/138830763/325081429-d02bcdb2-bb2e-47c5-a3d6-a85ef3fb6031.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzU5MjcsIm5iZiI6MTcxNDEzNTYyNywicGF0aCI6Ii8xMzg4MzA3NjMvMzI1MDgxNDI5LWQwMmJjZGIyLWJiMmUtNDdjNS1hM2Q2LWE4NWVmM2ZiNjAzMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQxMjQ3MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDlhZGI3NzE0YTk3NzM3NjllNDMxMTRhMTQwMDAxODYxN2I2Zjk0ZTVlYWE2Y2EyODY5ODFlMDgxYjM5MTJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f8IXu4bk2avspiXNo4yqMIHvndiHudTgl-OHSYK5Uco) Hello 👋 I hope everyone is well I would like to know how I can add a button to my project I have had more than 3 weeks without success
> 
> Português: Olá 👋 Espero que todos estejam bem. Gostaria de saber como posso adicionar um botão ao meu projeto. Já faz mais de 3 semanas sem sucesso.

Can you share me code of this reply message code ?
